### User Registration
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123",
  "role": "user"
}

### Admin Registration
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "adminuser",
  "password": "adminpassword",
  "role": "admin"
}

### User Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

### Admin Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "adminuser",
  "password": "adminpassword"
}

### Invalid Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "wrongpassword"
}

### Get All Tasks (Authenticated Users)
GET http://localhost:4000/api/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjM3ZDFmMzA2NjM1Y2JiMDQyOGQwYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0NTczNTcxLCJleHAiOjE3MzQ1NzcxNzF9.Kim3EwoV


### Create a Task (Admin Only)
POST http://localhost:4000/api/items
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjM3ZDQwMzA2NjM1Y2JiMDQyOGQwYyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDU3NDc2NiwiZXhwIjoxNzM0NTc4MzY2fQ.qsXusWtTaY4ZUhmcE2dC66H-YbwrTWbnk1f3_Uu0tuk
Content-Type: application/json

{
  "title": "New Task",
  "description": "Test task created by admin",
  "dueDate": "2024-12-31",
  "priority": "high",
  "completed": false
}

### Get Task by ID
GET http://localhost:4000/api/items/67636fd6a64f26e1fd9f10ba
Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjM3ZDFmMzA2NjM1Y2JiMDQyOGQwYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzM0NTczNDg0LCJleHAiOjE3MzQ1NzcwODR9.QEUYdbAbF7vhhirwBgxyroz3fUr0aNXi0YlkZev1F4Y>

### Update a Task (Admin Only)
PUT http://localhost:4000/api/items/67636fd6a64f26e1fd9f10ba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjM3ZDQwMzA2NjM1Y2JiMDQyOGQwYyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDU3NDc2NiwiZXhwIjoxNzM0NTc4MzY2fQ.qsXusWtTaY4ZUhmcE2dC66H-YbwrTWbnk1f3_Uu0tuk
Content-Type: application/json

{
  "title": "Reading",
  "time": "one hour",
  "priority": "medium",
  
}

### Delete a Task (Admin Only)
DELETE http://localhost:4000/api/items/67636fd6a64f26e1fd9f10ba
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjM3ZDQwMzA2NjM1Y2JiMDQyOGQwYyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNDU3NDc2NiwiZXhwIjoxNzM0NTc4MzY2fQ.qsXusWtTaY4ZUhmcE2dC66H-YbwrTWbnk1f3_Uu0tuk

### Register with Missing Fields
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "username": "userwithoutpassword"
}

### Access with Invalid Token
GET http://localhost:4000/api/items
Authorization: Bearer invalid.token.here

### Access Protected Route Without Token
GET http://localhost:4000/api/items
